# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_3_letter',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='airport',
            name='city_3_letter',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AlterField(
            model_name='airport',
            name='temperature',
            field=models.IntegerField(default=23),
        ),
        migrations.AlterField(
            model_name='airport',
            name='weather',
            field=models.CharField(choices=[('0', '晴'), ('1', '多云'), ('2', '少云'), ('3', '阴'), ('4', '雾')], default='晴', max_length=10),
        ),
    ]
