# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-03 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_auto_20190522_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='weather',
            field=models.CharField(default='晴', max_length=10),
        ),
    ]
