# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_trip', models.IntegerField(default=1)),
                ('flight_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplane.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('email', models.EmailField(default='123@qq.com', max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='保密', max_length=32)),
                ('birthday', models.DateField(default='1998-06-02')),
                ('access', models.IntegerField(default=1)),
                ('icon', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('phone', '手机'), ('username', '用户名')], default='手机', max_length=32)),
                ('identifier', models.CharField(max_length=254, unique=True)),
                ('credential', models.CharField(max_length=254)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='mytrip',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
