# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('secret', '保密')], default='保密', max_length=32)),
                ('birthday', models.DateField()),
                ('access', models.IntegerField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_type', models.CharField(choices=[('phone', '手机')], default='手机', max_length=32)),
                ('identifier', models.CharField(max_length=256)),
                ('credential', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
