# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(),
        ),
    ]
