# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190406_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='credential',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='identifier',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='identity_type',
            field=models.CharField(choices=[('phone', '手机'), ('username', '用户名')], default='手机', max_length=32),
        ),
    ]
