# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-20 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190420_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytrip',
            name='flight_ID',
        ),
        migrations.AddField(
            model_name='mytrip',
            name='flight_id',
            field=models.CharField(default='CA1113', max_length=100),
        ),
    ]
