# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
        ('user', '0003_auto_20190411_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airplane.Flight')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_auth',
            name='id',
        ),
        migrations.RemoveField(
            model_name='verifycode',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='1998-06-02'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='123@qq.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='credential',
            field=models.CharField(max_length=254, primary_key=True),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='identifier',
            field=models.CharField(max_length=254, primary_key=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user_auth',
            name='identity_type',
            field=models.CharField(choices=[('phone', '手机'), ('username', '用户名')], default='手机', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='code',
            field=models.CharField(max_length=8, primary_key=True),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='mobile',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='mytrip',
            name='user_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
