# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_terminal',
            field=models.CharField(default='--', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_terminal',
            field=models.CharField(default='--', max_length=10),
        ),
    ]
