# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0002_auto_20190522_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='Baggage_num',
            field=models.CharField(default='--', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arriving_port',
            field=models.CharField(default='--', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='boarding_port',
            field=models.CharField(default='--', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='check_in',
            field=models.CharField(default='--', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='delay_time',
            field=models.CharField(default='--', max_length=30),
        ),
        migrations.AlterField(
            model_name='flight',
            name='punctuality_rate',
            field=models.CharField(default='--', max_length=30),
        ),
    ]
