# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-25 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airplane', '0004_auto_20190522_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='detail_url',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
